// 互联网冲浪人格测试 - 24 种人格图鉴

const personalityTypes = [
  {
    code: 'DOUYIN',
    name: '抖音圣体',
    category: '热梗现行犯',
    icon: '📱',
    accent: '#ff6b4a',
    rarity: 'SR',
    pattern: { M1: 'H', M2: 'M', M3: 'M', M4: 'H', M5: 'M', M6: 'H', M7: 'M', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '平台一刷你就醒，人类一喊你没空。',
    description: '你和抖音的关系已经不是“使用”，而是“共生”。新梗没热你先会，BGM没火你先存，现实生活像番外，主线永远在推荐页。',
    roast: '别人是拿手机上网，你像是给平台当驻站员工。',
    traits: ['热梗秒懂', '推荐页原住民', '收藏先行', '断网就慌']
  },
  {
    code: 'FUDUJI',
    name: '热梗复读机',
    category: '热梗现行犯',
    icon: '📣',
    accent: '#ff8a5b',
    rarity: 'R',
    pattern: { M1: 'H', M2: 'L', M3: 'M', M4: 'H', M5: 'L', M6: 'H', M7: 'L', M8: 'M', M9: 'M', M10: 'H' },
    slogan: '梗不是你发明的，但你一定是最勤快的搬运工。',
    description: '你最大的天赋，是把一句破梗念出流水线质感。群里一句、评论区一句、朋友圈再补一句，哪怕笑点过保，你也能硬续三天。',
    roast: '你不是在表达自己，你是在给热梗做售后。',
    traits: ['见梗就跟', '扩散型选手', '语言模板化', '过气不自知']
  },
  {
    code: 'CHOUXIANG',
    name: '抽象带师',
    category: '热梗现行犯',
    icon: '🌀',
    accent: '#ff4d6d',
    rarity: 'SSR',
    pattern: { M1: 'H', M2: 'M', M3: 'H', M4: 'H', M5: 'H', M6: 'M', M7: 'L', M8: 'H', M9: 'H', M10: 'M' },
    slogan: '正常说话你嫌平，非得把场子扭成行为艺术。',
    description: '你活着就像在给互联网供素材。别人整活靠准备，你整活靠本能，哪怕只是回一句“收到”，都得回出点让人怀疑精神状态的味。',
    roast: '你不是抽象，你是把聊天窗口当精神病汇报厅。',
    traits: ['无痛发癫', '即兴整活', '抽象表达', '名场面制造']
  },
  {
    code: 'BGMQIHAO',
    name: 'BGM起号怪',
    category: '热梗现行犯',
    icon: '🎵',
    accent: '#7c5cff',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'M', M4: 'H', M5: 'H', M6: 'M', M7: 'L', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '什么都没发生，但你脑子里已经自动响起前奏。',
    description: '你看世界自带短视频剪辑轨道，走路能配 BGM，自拍要挑情绪，连发条动态都像在给自己剪预告片。气氛没到位，你连字都懒得打。',
    roast: '你不是过日子，你是在给一个并不存在的账号养号。',
    traits: ['BGM上脑', '镜头感强', '氛围先行', '日常短视频化']
  },
  {
    code: 'KAOGU',
    name: '电子考古学家',
    category: '热梗现行犯',
    icon: '🔎',
    accent: '#3a86ff',
    rarity: 'SR',
    pattern: { M1: 'H', M2: 'L', M3: 'L', M4: 'M', M5: 'M', M6: 'L', M7: 'L', M8: 'H', M9: 'M', M10: 'M' },
    slogan: '别人看热闹，你负责把祖坟都刨出来。',
    description: '你遇到一个新梗，第一反应不是跟，而是追根溯源。你能从一句评论倒推三次事件、四个旧帖和五个过气版本，吃瓜姿势比当事人还完整。',
    roast: '你不是冲浪，你是在互联网遗址里做田野调查。',
    traits: ['会找源头', '时间线狂魔', '旧帖翻新', '反转预备役']
  },
  {
    code: 'BIAOQING',
    name: '表情包外交官',
    category: '热梗现行犯',
    icon: '🖼️',
    accent: '#f2a541',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'M', M4: 'H', M5: 'M', M6: 'H', M7: 'L', M8: 'M', M9: 'M', M10: 'M' },
    slogan: '你的发言不靠字，靠库存。',
    description: '你擅长用一张图解决三十句废话。吵架靠包，安慰靠包，破冰靠包，嘴上说“懒得打字”，其实是早就把所有情绪做成分类文件夹了。',
    roast: '你不是高情商，你只是会拿别人的脸替自己说话。',
    traits: ['图库充足', '无字输出', '表情先手', '社交减负']
  },
  {
    code: 'JIANPAN',
    name: '键盘判官',
    category: '评论区作战部',
    icon: '⚖️',
    accent: '#ff5a5f',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'H', M3: 'M', M4: 'H', M5: 'L', M6: 'M', M7: 'M', M8: 'M', M9: 'M', M10: 'M' },
    slogan: '案子还没看全，你的判决书已经写完了。',
    description: '你刷到一个事件，最先起飞的是立场而不是脑子。谁对谁错你不一定真懂，但语气一定够笃定，仿佛平台没你坐镇早就乱成一锅粥。',
    roast: '你不是正义，你只是比别人更爱抢审判席。',
    traits: ['先判后看', '立场起手', '语气很满', '评论区开庭']
  },
  {
    code: 'YINYANG',
    name: '阴阳宗师',
    category: '评论区作战部',
    icon: '☯️',
    accent: '#8b5cf6',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'M', M3: 'H', M4: 'M', M5: 'M', M6: 'M', M7: 'M', M8: 'M', M9: 'H', M10: 'L' },
    slogan: '你说话的目标不是交流，是精准让人难受。',
    description: '你从不正面打人，但每句话都像从棉花里藏了针。明面上是客气，落点全是膈应，别人还没法直接翻脸，只能憋着回家复盘。',
    roast: '你以为自己高级，其实只是把坏好好包装了一下。',
    traits: ['拐弯扎人', '礼貌带刺', '句尾有毒', '让人回味']
  },
  {
    code: 'GANGJING',
    name: '杠精永动机',
    category: '评论区作战部',
    icon: '🧱',
    accent: '#ff7b00',
    rarity: 'R',
    pattern: { M1: 'L', M2: 'H', M3: 'M', M4: 'H', M5: 'M', M6: 'M', M7: 'M', M8: 'M', M9: 'L', M10: 'M' },
    slogan: '别人发观点，你发体力。',
    description: '你的人生乐趣之一，就是在别人说“我觉得”后面接一句“那可不一定”。你不一定真有结论，但你一定不能让对面太轻松地下线。',
    roast: '你不是在讨论问题，你是在给互联网做阻力训练。',
    traits: ['抬杠成瘾', '反驳本能', '逻辑续杯', '嘴比脑快']
  },
  {
    code: 'RESHOU',
    name: '热搜审判长',
    category: '评论区作战部',
    icon: '🧾',
    accent: '#ff3d71',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'H', M3: 'M', M4: 'H', M5: 'L', M6: 'L', M7: 'M', M8: 'H', M9: 'H', M10: 'M' },
    slogan: '每一条热搜，都该由你来定性。',
    description: '你对热点有一种天然责任感，仿佛不写两段判词事情就不算结束。资料看不看全另说，但结论一定要抢在反转之前发出去。',
    roast: '你不是吃瓜群众，你是瓜田里最忙的居委会。',
    traits: ['热搜冲锋', '点评欲强', '结论先出', '上纲上线']
  },
  {
    code: 'FANZHUAN',
    name: '反转预言家',
    category: '评论区作战部',
    icon: '🔁',
    accent: '#06b6d4',
    rarity: 'SR',
    pattern: { M1: 'H', M2: 'M', M3: 'M', M4: 'M', M5: 'L', M6: 'L', M7: 'L', M8: 'H', M9: 'H', M10: 'M' },
    slogan: '瓜还没熟，你已经在评论区先埋伏笔。',
    description: '你最大的爱好，是在全网站队最凶的时候幽幽留下一句“先别急”。有时你是真有经验，有时你只是享受事后回帖那句“我早说了吧”。',
    roast: '你的人生高光，不是看懂了，而是赌中了。',
    traits: ['先留后手', '爱看翻车', '逆风埋点', '事后补刀']
  },
  {
    code: 'LEZI',
    name: '赛博乐子人',
    category: '评论区作战部',
    icon: '🍿',
    accent: '#ef476f',
    rarity: 'SSR',
    pattern: { M1: 'H', M2: 'M', M3: 'H', M4: 'H', M5: 'H', M6: 'M', M7: 'L', M8: 'H', M9: 'M', M10: 'H' },
    slogan: '你的立场只有一个，就是别停。',
    description: '你不一定关心谁赢，但你一定关心节目效果够不够。看到对线、翻车、互锤、补录、道歉、反转，你的眼睛比平台推荐算法还亮。',
    roast: '别人吃瓜是消遣，你吃瓜像在给自己充电。',
    traits: ['节目效果优先', '拱火不嫌事大', '站边随缘', '全程追更']
  },
  {
    code: 'CANGSHU',
    name: '电子仓鼠',
    category: '赛博生存组',
    icon: '🐹',
    accent: '#22c55e',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'L', M4: 'H', M5: 'L', M6: 'L', M7: 'M', M8: 'L', M9: 'L', M10: 'H' },
    slogan: '你不一定发言，但一定在偷偷囤东西。',
    description: '你冲浪的核心动作不是输出，而是收藏。教程先存，文案先存，笑话先存，瓜先截图，虽然大部分你永远不会再打开，但存到就是赚到。',
    roast: '你的收藏夹像仓库，问题是你从来不出库。',
    traits: ['见啥都存', '截图成习惯', '囤积快乐', '输出偏少']
  },
  {
    code: 'SHOUCANG',
    name: '收藏夹囤囤鼠',
    category: '赛博生存组',
    icon: '📂',
    accent: '#14b8a6',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'L', M4: 'M', M5: 'M', M6: 'M', M7: 'L', M8: 'L', M9: 'H', M10: 'M' },
    slogan: '会不会做以后再说，先加入“以后一定会看”。',
    description: '你的冲浪逻辑很朴素: 看到有用的先存，看到好笑的先存，看到像能改变人生的也先存。你很擅长给未来的自己画饼，并把饼整齐塞进文件夹。',
    roast: '你的知识体系，全都躺在“稍后再看”里睡大觉。',
    traits: ['收藏成瘾', '以后再看', '教程囤积', '执行缓慢']
  },
  {
    code: 'EMO',
    name: '深夜 emo 机',
    category: '赛博生存组',
    icon: '🌙',
    accent: '#5b5f97',
    rarity: 'SR',
    pattern: { M1: 'L', M2: 'L', M3: 'M', M4: 'H', M5: 'L', M6: 'L', M7: 'H', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '白天像个路人，半夜像在给全网写遗书。',
    description: '你白天刷梗，夜里刷情绪。音乐一响、灯一关、消息一静，你就自动进入长夜模式，别人只是失眠，你是顺便把人生也复盘了。',
    roast: '你的情绪管理方式，就是给自己配个滤镜然后继续难过。',
    traits: ['深夜上线', '情绪泛滥', '文案伤感', '夜间高活跃']
  },
  {
    code: 'DUANWANG',
    name: '断网失联体',
    category: '赛博生存组',
    icon: '📵',
    accent: '#111827',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'L', M3: 'L', M4: 'H', M5: 'L', M6: 'M', M7: 'M', M8: 'L', M9: 'M', M10: 'H' },
    slogan: '网一断，你整个人像掉出世界地图。',
    description: '你不是离不开手机，你是离不开“随时有事发生”的感觉。没有信号、没有更新、没有新消息时，你连发呆都发不安稳。',
    roast: '别人断网叫休息，你断网像在体验灵魂抽离。',
    traits: ['低电恐慌', '消息依赖', '平台续命', '离线不安']
  },
  {
    code: 'QIANSHUI',
    name: '社交潜水艇',
    category: '赛博生存组',
    icon: '🤿',
    accent: '#64748b',
    rarity: 'N',
    pattern: { M1: 'M', M2: 'L', M3: 'L', M4: 'M', M5: 'L', M6: 'L', M7: 'L', M8: 'L', M9: 'L', M10: 'M' },
    slogan: '你一直都在，但你就是不冒头。',
    description: '你看得比谁都全，发得比谁都少。群聊消息你能从头读到尾，热点你也都知道，只是你永远停在输入框前面那一步。',
    roast: '你不是社恐，你是把存在感调成了省电模式。',
    traits: ['长期潜水', '全程围观', '少量发言', '稳定隐身']
  },
  {
    code: 'YIDUBUHUI',
    name: '已读不回仙人',
    category: '赛博生存组',
    icon: '🫥',
    accent: '#94a3b8',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'H', M4: 'M', M5: 'L', M6: 'L', M7: 'L', M8: 'L', M9: 'M', M10: 'L' },
    slogan: '消息看得很快，回复看缘分。',
    description: '你不是没看到，你只是懒得立刻进入对话。很多消息在你这里会先被“心里回复”一次，然后安详地躺进已读区，直到对面怀疑人生。',
    roast: '你最大的社交技巧，就是让别人主动替你找借口。',
    traits: ['高频已读', '低频回复', '心里回过', '聊天拖延']
  },
  {
    code: 'ZHENGHUO',
    name: '整活导演',
    category: '整活出道班',
    icon: '🎥',
    accent: '#f97316',
    rarity: 'SSR',
    pattern: { M1: 'H', M2: 'M', M3: 'M', M4: 'H', M5: 'H', M6: 'M', M7: 'L', M8: 'H', M9: 'H', M10: 'H' },
    slogan: '安静不是你的风格，起码得有个包袱落地。',
    description: '你对“内容”有一种天然执念。一个普通群聊在你手里能盘成综艺，一个普通自拍你能写出整套剧情，任何无聊时刻都可能被你现场拍成番外篇。',
    roast: '你不是不会安静，你是怕一安静就显得自己没节目。',
    traits: ['导演视角', '场面控制', '包袱密度高', '内容脑']
  },
  {
    code: 'SHEJIANNIU',
    name: '赛博社牛',
    category: '整活出道班',
    icon: '🪩',
    accent: '#fb7185',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'M', M3: 'L', M4: 'H', M5: 'H', M6: 'M', M7: 'L', M8: 'M', M9: 'H', M10: 'M' },
    slogan: '你在网上没有陌生人，只有还没被你搭上的人。',
    description: '你很会制造热络感，见谁都能聊，在哪都能接话。别人还在观察气氛，你已经把楼搭好了，顺手还把自己的存在感也抬上去了。',
    roast: '你不是自来熟，你是把所有公共场合都当自己直播间。',
    traits: ['敢接陌生话', '氛围拉满', '输出稳定', '社交无门槛']
  },
  {
    code: 'YOUMU',
    name: '热点游牧民',
    category: '整活出道班',
    icon: '🧭',
    accent: '#f59e0b',
    rarity: 'SR',
    pattern: { M1: 'H', M2: 'M', M3: 'M', M4: 'H', M5: 'M', M6: 'H', M7: 'L', M8: 'H', M9: 'H', M10: 'H' },
    slogan: '哪里热，你的人格就迁到哪里。',
    description: '你没有固定主场，哪个平台有瓜、哪条赛道有梗，你就出现在哪。你的账号像移动摊位，今天玩抽象，明天蹭反转，后天换个 BGM 继续营业。',
    roast: '你的人设不是稳定，是实时跟着流量搬家。',
    traits: ['四处巡游', '热点贴脸', '适应极快', '站位灵活']
  },
  {
    code: 'LIANAINAO',
    name: '赛博恋爱脑',
    category: '整活出道班',
    icon: '💘',
    accent: '#ec4899',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'M', M4: 'H', M5: 'M', M6: 'M', M7: 'H', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '别人刷短视频，你刷爱情幻灯片。',
    description: '你很容易把一点关注脑补成连续剧，把一句关心当作人物关系升温。别人发自拍你看眼妆，你看缘分，别人发文案你看格式，你看暗示。',
    roast: '你不是懂爱，你只是特别擅长给自己加戏。',
    traits: ['细节上头', '脑补能力强', '情绪易挂钩', '感情滤镜厚']
  },
  {
    code: 'QINGXING',
    name: '人间清醒哥',
    category: '整活出道班',
    icon: '🧊',
    accent: '#0f766e',
    rarity: 'SR',
    pattern: { M1: 'L', M2: 'L', M3: 'H', M4: 'L', M5: 'L', M6: 'L', M7: 'L', M8: 'L', M9: 'L', M10: 'L' },
    slogan: '别人上头，你负责泼冷水并顺手讲道理。',
    description: '你不是完全不玩梗，只是很少让自己掉进梗里。看热闹时你先撤半步，看对线时你先想后果，看别人发疯时你第一反应是“这事值吗”。',
    roast: '你最大的缺点，就是有时候真的太像班主任。',
    traits: ['低波动', '理性旁观', '不易跟风', '降温选手']
  },
  {
    code: 'HUOREN',
    name: '冲浪活人王',
    category: '整活出道班',
    icon: '🫡',
    accent: '#2563eb',
    rarity: 'UR',
    pattern: { M1: 'M', M2: 'M', M3: 'L', M4: 'M', M5: 'M', M6: 'L', M7: 'L', M8: 'M', M9: 'L', M10: 'M' },
    slogan: '会玩，但不疯；能跟，但不被梗牵着鼻子走。',
    description: '你是互联网稀有物种: 既能懂梗，又不会被梗吞掉；既能参与，又不会全天候表演；既能看热闹，也知道什么时候该下线。你像正常人，但又比正常人多一点网感。',
    roast: '恭喜你在互联网还保住了点人味，这已经很奢侈了。',
    traits: ['懂梗有度', '参与适中', '能聊能撤', '稳定活人']
  }
];

const fallbackType = {
  code: 'YUANZHU',
  name: '互联网野生号',
  category: '未分类',
  icon: '🛰️',
  accent: '#475569',
  rarity: 'UR',
  pattern: {},
  slogan: '你不太像任何一种典型样本，主打一个野路子在线。',
  description: '现有图鉴没把你装进去，说明你的冲浪姿势要么过于平均，要么过于歪门。你不是完全没网感，只是平台一时半会儿还没给你命名。',
  roast: '别人是互联网人格，你像系统随机刷出来的游客号。',
  traits: ['未被命名', '野生冲浪', '难以归类', '自由散养']
};

const rarityGuide = {
  N: { label: '普通款', color: '#7f7b7a', chance: '常见' },
  R: { label: '稀有款', color: '#2f7f87', chance: '偏常见' },
  SR: { label: '高能款', color: '#b45c2b', chance: '少见' },
  SSR: { label: '名场面', color: '#df8b1d', chance: '很少见' },
  UR: { label: '传说皮肤', color: '#b72222', chance: '极少见' }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { personalityTypes, fallbackType, rarityGuide };
}
