// 互联网冲浪人格测试 - 21 种人格图鉴
const personalityTypes = [
  {
    code: 'XYY',
    name: '性压抑',
    category: '热梗全明星',
    icon: '🧷',
    accent: '#ff6b7a',
    rarity: 'SSR',
    pattern: { M1: 'H', M2: 'L', M3: 'M', M4: 'H', M5: 'M', M6: 'M', M7: 'H', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '别人听峰哥讲逻辑，你在评论区等车开起来。',
    description: '你刷到两性话题总能秒进状态，表面像在分析社会观察，实际脑内早把暧昧、拉扯和连接演了三季。越是一本正经的讨论，你越能从缝里闻到那点不对劲的味。',
    roast: '你不是理解力强，你是见什么都想往暧昧频道上接。',
    traits: ['峰哥受害者', '暧昧雷达', '脑补拉满', '评论区开车']
  },
  {
    code: 'APPLE',
    name: '苹果人',
    category: '热梗全明星',
    icon: '🍎',
    accent: '#8d99ae',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'M', M3: 'M', M4: 'H', M5: 'L', M6: 'L', M7: 'M', M8: 'L', M9: 'H', M10: 'H' },
    slogan: '没人问你用什么机子，你已经把生态讲完了。',
    description: '你对苹果的感情早就超过电子产品，已经接近人生立场。别人聊参数你聊手感，别人聊性价比你聊审美，哪怕手机壳都得带一种“我和你们不一样”的味。',
    roast: '你买的不是手机，是一张能随时抬下巴的入场券。',
    traits: ['生态信仰', '灵动岛人格', '审美优越', '线下展示']
  },
  {
    code: 'LAOSHU',
    name: '老鼠人',
    category: '热梗全明星',
    icon: '🐭',
    accent: '#7a5c58',
    rarity: 'SR',
    pattern: { M1: 'L', M2: 'L', M3: 'L', M4: 'H', M5: 'L', M6: 'L', M7: 'M', M8: 'L', M9: 'L', M10: 'H' },
    slogan: '吃着拼好饭，熬着最阴的夜。',
    description: '你的人生主线是低成本续命，高频率上网。白天像系统待机，晚上开始活，拼好饭、外卖袋和发光屏幕，基本就是你最稳定的精神家园。',
    roast: '你不是省，你是把活着压缩成了最低功耗模式。',
    traits: ['拼好饭常客', '昼伏夜出', '低配续命', '房间常暗']
  },
  {
    code: 'PANGMAO',
    name: '胖猫',
    category: '热梗全明星',
    icon: '🐟',
    accent: '#4d7298',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'L', M3: 'L', M4: 'H', M5: 'L', M6: 'L', M7: 'H', M8: 'M', M9: 'L', M10: 'H' },
    slogan: '真心给得太快，情绪掉得也快。',
    description: '你这种人一上头就容易把感情当主线，把自己当支线。白天嘴上说算了，晚上还是会切回聊天记录、旧歌单和游戏房间，反复确认那点没落地的真心。',
    roast: '你不是恋爱脑，你是情绪一来就给自己开无限重播。',
    traits: ['深情上头', '夜里复盘', '旧记录考古', '下头困难']
  },
  {
    code: 'GUINAN',
    name: '龟男',
    category: '热梗全明星',
    icon: '🐢',
    accent: '#4f772d',
    rarity: 'R',
    pattern: { M1: 'L', M2: 'L', M3: 'L', M4: 'M', M5: 'L', M6: 'L', M7: 'H', M8: 'L', M9: 'M', M10: 'M' },
    slogan: '委屈全吞了，聊天框还在回好的。',
    description: '你总爱把自己的需求往后排，主打一个先照顾别人情绪。嘴上说没事，心里已经写了三千字不服，但最后还是会自己消化，然后继续装成那个最好说话的人。',
    roast: '你不是温柔，你是太会拿自己给别人打补丁。',
    traits: ['过度让步', '嘴硬心软', '委屈复读', '内耗专家']
  },
  {
    code: 'VALO',
    name: '瓦学弟',
    category: '热梗全明星',
    icon: '🔫',
    accent: '#ff5d5d',
    rarity: 'SR',
    pattern: { M1: 'H', M2: 'H', M3: 'M', M4: 'H', M5: 'H', M6: 'M', M7: 'H', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '还没进房，你的情绪和语音已经热身完了。',
    description: '你天生适合把竞技游戏打成情绪综艺，尤其一进语音就像被点了开机键。嘴上说再来一把，实际是把输赢、面子和兄弟义气全塞进了同一个回合里。',
    roast: '你不是在打游戏，你是在拿排位练人格强度。',
    traits: ['语音上头', '枪男文学', '输赢挂脸', '兄弟局开演']
  },
  {
    code: 'GO',
    name: 'GO学长',
    category: '热梗全明星',
    icon: '🎯',
    accent: '#f18f01',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'H', M3: 'H', M4: 'M', M5: 'M', M6: 'L', M7: 'M', M8: 'L', M9: 'M', M10: 'M' },
    slogan: '老登气质不一定大，但战术口气必须够老。',
    description: '你身上有种很典型的老派电竞味，讲究站位、残局、意识和那点资历感。哪怕只是路人局，你也能说得像在带青训，仿佛所有人都该先听你讲两句。',
    roast: '你不是经验多，你是太爱把每局都打成开班授课。',
    traits: ['老派枪男', '战术口气', '残局嘴硬', '资历感重']
  },
  {
    code: 'JIAHAO',
    name: '嘉豪',
    category: '热梗全明星',
    icon: '😎',
    accent: '#7c4dff',
    rarity: 'SSR',
    pattern: { M1: 'H', M2: 'M', M3: 'M', M4: 'H', M5: 'H', M6: 'H', M7: 'L', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '一开口就像短视频里的自信口播男主。',
    description: '你身上那股“我来给你们说句实话”的气质特别重，哪怕只是分享日常，也能讲成一段气口很满的个人观点。最擅长在普通场景里，抬出一股莫名其妙的主角感。',
    roast: '你不是自信，你是随时准备把生活配成口播 BGM。',
    traits: ['口播腔', '主角感重', '观点先行', '气口很满']
  },
  {
    code: 'FUDUJI',
    name: '热梗复读机',
    category: '评论区现行犯',
    icon: '📣',
    accent: '#ff8a5b',
    rarity: 'R',
    pattern: { M1: 'H', M2: 'L', M3: 'M', M4: 'H', M5: 'L', M6: 'H', M7: 'L', M8: 'M', M9: 'M', M10: 'H' },
    slogan: '梗不是你发明的，但一定是你扩散的。',
    description: '你上网最大的贡献，就是让一条热梗在不同群聊继续活下去。哪怕笑点已经过保，你也能稳定复读三天，主打一个自己不产梗，但绝不让梗冷死。',
    roast: '你不是在表达自己，你是在给热梗做售后。',
    traits: ['见梗就跟', '扩散选手', '复读成瘾', '过气不知']
  },
  {
    code: 'CHOUXIANG',
    name: '抽象带师',
    category: '评论区现行犯',
    icon: '🌀',
    accent: '#ff4d6d',
    rarity: 'SSR',
    pattern: { M1: 'H', M2: 'M', M3: 'H', M4: 'H', M5: 'H', M6: 'M', M7: 'L', M8: 'H', M9: 'H', M10: 'M' },
    slogan: '正常说话太没劲，你非得把场子拧歪。',
    description: '你有一种把任何聊天都往抽象区带的本事，别人还在说事情，你已经开始造画面。很多人以为你在发疯，其实你只是觉得平铺直叙太浪费这张嘴。',
    roast: '你不是抽象，你是把聊天框当行为艺术展厅。',
    traits: ['即兴整活', '无痛发疯', '画面生成', '抽象表达']
  },
  {
    code: 'LEZI',
    name: '赛博乐子人',
    category: '评论区现行犯',
    icon: '🍉',
    accent: '#ef476f',
    rarity: 'SSR',
    pattern: { M1: 'H', M2: 'M', M3: 'H', M4: 'H', M5: 'H', M6: 'M', M7: 'L', M8: 'H', M9: 'M', M10: 'H' },
    slogan: '你不站队，你只站节目效果。',
    description: '你对任何热点的兴趣都不在真相，而在戏够不够大。只要有对线、翻车、补录、反转，你就像打了鸡血一样追更，哪边赢不重要，别停更最重要。',
    roast: '别人吃瓜是消遣，你吃瓜像在追连续剧。',
    traits: ['节目效果党', '拱火轻熟', '反转续杯', '围观上瘾']
  },
  {
    code: 'JIANPAN',
    name: '键盘判官',
    category: '评论区现行犯',
    icon: '⌨️',
    accent: '#ff5a5f',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'H', M3: 'M', M4: 'H', M5: 'L', M6: 'M', M7: 'M', M8: 'M', M9: 'M', M10: 'M' },
    slogan: '资料没看完，判词已经写完了。',
    description: '你刷到一件事，最先启动的不是理解力，是裁决欲。谁对谁错你未必真弄明白，但你一定会抢在第二波反转前，把自己的立场打得像结案陈词一样硬。',
    roast: '你不是正义，你只是太爱坐审判席。',
    traits: ['先判后看', '立场拉满', '语气封顶', '评论区开庭']
  },
  {
    code: 'YINYANG',
    name: '阴阳宗师',
    category: '评论区现行犯',
    icon: '🗡️',
    accent: '#8b5cf6',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'M', M3: 'H', M4: 'M', M5: 'M', M6: 'M', M7: 'M', M8: 'M', M9: 'H', M10: 'L' },
    slogan: '嘴上没脏字，落点全是刀。',
    description: '你很少正面狠狠干人，但特别会把一句话说得让对面回家复盘。表面礼貌，内里扎人，别人想翻脸都缺证据，只能自己在脑子里越想越不对。',
    roast: '你不是高情商，你只是把恶意包装得比较精致。',
    traits: ['礼貌带刺', '拐弯扎人', '句尾有毒', '回味很久']
  },
  {
    code: 'KAOGU',
    name: '电子考古学家',
    category: '评论区现行犯',
    icon: '🕵️',
    accent: '#3a86ff',
    rarity: 'SR',
    pattern: { M1: 'H', M2: 'L', M3: 'L', M4: 'M', M5: 'M', M6: 'L', M7: 'L', M8: 'H', M9: 'M', M10: 'M' },
    slogan: '别人看热闹，你负责把前情翻全。',
    description: '你看到一个新瓜，第一反应不是选边站，而是刨源头。旧帖、旧评、旧截图、旧时间线你都能翻出来，硬是把一场实时热闹做成一份互联网田野调查。',
    roast: '你不是冲浪，你是在网里做考古发掘。',
    traits: ['前情补全', '旧帖翻新', '时间线狂魔', '反转预备']
  },
  {
    code: 'BGM',
    name: 'BGM起号怪',
    category: '赛博生存组',
    icon: '🎵',
    accent: '#7c5cff',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'M', M4: 'H', M5: 'H', M6: 'M', M7: 'L', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '你的人生没那么多剧情，但脑内配乐一秒不停。',
    description: '你看世界自带短视频剪辑轨道，走路要有 BGM，自拍要有氛围，连发个动态都像在给自己做预告片。内容能不能打先不说，气质必须先到位。',
    roast: '你不是在过日子，你是在运营一个并不存在的账号。',
    traits: ['氛围优先', '镜头脑', '自带 BGM', '生活预告片']
  },
  {
    code: 'BIAOQING',
    name: '表情包外交官',
    category: '赛博生存组',
    icon: '🫠',
    accent: '#f2a541',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'M', M4: 'M', M5: 'M', M6: 'H', M7: 'L', M8: 'L', M9: 'M', M10: 'M' },
    slogan: '你的人际关系，全靠库存表情包维稳。',
    description: '很多话你懒得打，但你很懂哪张图该在什么时候发。安慰靠包，敷衍靠包，破冰靠包，阴阳也靠包，主打一个能不亲自说就不亲自说。',
    roast: '你不是懒，你是把社交外包给了图库。',
    traits: ['库存很深', '无字输出', '表情先手', '社交省电']
  },
  {
    code: 'CANGSHU',
    name: '电子仓鼠',
    category: '赛博生存组',
    icon: '🐹',
    accent: '#22c55e',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'L', M4: 'H', M5: 'L', M6: 'L', M7: 'M', M8: 'L', M9: 'L', M10: 'H' },
    slogan: '先存着，以后未必看，但不能没有。',
    description: '你冲浪的核心动作不是发言，是收藏。教程要存，笑话要存，截图要存，哪怕以后根本翻不到也得先塞进夹里，仿佛存到了就等于学到了。',
    roast: '你的收藏夹像仓库，问题是从来不出库。',
    traits: ['看见就存', '截图成瘾', '以后再说', '囤积快乐']
  },
  {
    code: 'EMO',
    name: '深夜emo机',
    category: '赛博生存组',
    icon: '🌙',
    accent: '#5b5f97',
    rarity: 'SR',
    pattern: { M1: 'L', M2: 'L', M3: 'M', M4: 'H', M5: 'L', M6: 'L', M7: 'H', M8: 'M', M9: 'H', M10: 'H' },
    slogan: '白天像路人，半夜像在给全网写遗书。',
    description: '你白天刷梗，夜里刷情绪，一到安静时段就开始自动进入内心戏。歌单、旧事、聊天记录轮着来，别人是失眠，你是顺便把人生也复盘了一遍。',
    roast: '你不是感性，你是太擅长在深夜给自己加戏。',
    traits: ['夜间高活', '情绪回潮', '歌单刀人', '旧事循环']
  },
  {
    code: 'YIDU',
    name: '已读不回仙人',
    category: '赛博生存组',
    icon: '👁️',
    accent: '#94a3b8',
    rarity: 'R',
    pattern: { M1: 'M', M2: 'L', M3: 'H', M4: 'M', M5: 'L', M6: 'L', M7: 'L', M8: 'L', M9: 'M', M10: 'L' },
    slogan: '消息看得很快，回复全看天意。',
    description: '你不是没看到，你只是懒得立刻进入一段对话。很多消息会先在心里回一遍，然后安静地躺进已读区，直到对面开始怀疑自己是不是说错了什么。',
    roast: '你最大的社交技巧，就是逼别人替你脑补借口。',
    traits: ['高频已读', '低频回复', '心里回过', '聊天拖延']
  },
  {
    code: 'DUANWANG',
    name: '断网失联体',
    category: '赛博生存组',
    icon: '📵',
    accent: '#111827',
    rarity: 'SR',
    pattern: { M1: 'M', M2: 'L', M3: 'L', M4: 'H', M5: 'L', M6: 'M', M7: 'M', M8: 'L', M9: 'M', M10: 'H' },
    slogan: '网一断，你整个人像被踢出服务器。',
    description: '你离不开的不是手机，是随时有新东西发生的感觉。没信号、没更新、没消息时，你整个人都会开始发空，仿佛世界还在转，只有你被暂时除名了。',
    roast: '别人断网叫休息，你断网像魂被热更新卸载。',
    traits: ['低电恐慌', '更新依赖', '平台续命', '离线不安']
  },
  {
    code: 'HUOREN',
    name: '互联网活人',
    category: '赛博生存组',
    icon: '🙂',
    accent: '#2563eb',
    rarity: 'UR',
    pattern: { M1: 'M', M2: 'M', M3: 'L', M4: 'M', M5: 'M', M6: 'L', M7: 'L', M8: 'M', M9: 'L', M10: 'M' },
    slogan: '会玩梗，但没把自己彻底玩没。',
    description: '你是互联网里难得还保留点活人感的那批人。梗你懂，热闹你看，评论你能回，但不会把所有情绪、观点和存在感都挂到网上，属于还有下线按钮的人。',
    roast: '能在网里活成正常人，这已经算隐藏款了。',
    traits: ['网感适中', '能聊能撤', '不上头', '活人气息']
  }
];

const fallbackType = {
  code: 'WILD',
  name: '互联网野号',
  category: '未分类样本',
  icon: '🛰️',
  accent: '#475569',
  rarity: 'UR',
  pattern: {},
  slogan: '你不太像任何典型样本，主打一个野路子在线。',
  description: '现有图鉴暂时没把你彻底装进去，说明你的冲浪姿势要么过于平均，要么歪得很有自己的路数。平台一时半会还没给你起名，但这并不妨碍你继续在网里野蛮生长。',
  roast: '别人是互联网人格，你像系统随机刷出来的隐藏游客号。',
  traits: ['未被命名', '野生冲浪', '难以归类', '自由散养']
};

const rarityGuide = {
  N: { label: '普通款', color: '#7f7b7a', chance: '常见' },
  R: { label: '稀有款', color: '#2f7f87', chance: '偏常见' },
  SR: { label: '高能款', color: '#b45c2b', chance: '少见' },
  SSR: { label: '名场面', color: '#df8b1d', chance: '很少见' },
  UR: { label: '传说皮肤', color: '#b72222', chance: '极少见' }
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { personalityTypes, fallbackType, rarityGuide };
}
